[build]
  command = "npm install && npm run build"
  functions =  "functions"
[[headers]]
  for = "http://localhost:3000/"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "http://localhost:3000/"
  to = "https://image-server.netlify.app/.netlify/functions/index/upload-single-file"
  status = 200
