[build]
  command = "npm install && npm run build"
  functions =  "functions"
[[headers]]
  for = "/home"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/home"
  to = "https://image-server.netlify.app/.netlify/functions/index/upload-single-file"
  status = 200
