[build]
  command = "npm install && npm run build"
  functions =  "functions"
 [[redirects]]
  from = "/*"
  to = "https://image-server.netlify.app/.netlify/functions/index/upload-single-file"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"